service: academy
image: gambala/academy
servers:
  - <%= ENV["MAIN_SERVER_IP"] %>
labels:
  traefik.http.routers.academy-web.rule: Host(`academy.gambala.pro`)
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: gambala
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
    - DB_HOST
    - DB_PORT
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - REDIS_HOST
    - REDIS_PORT
    - WEB_CONCURRENCY
    - RAILS_MAX_THREADS
accessories:
  db:
    image: postgres:15
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV["DB_PORT"] %>:5432
    env:
      secret:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    host: <%= ENV["REDIS_HOST"] %>
    port: <%= ENV["REDIS_PORT"] %>:6379
    directories:
      - data:/data
traefik:
  args:
    api.dashboard: true
  labels:
    traefik.enable: true
    traefik.http.routers.dashboard.rule: Host(`traefik.gambala.pro`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
    traefik.http.routers.dashboard.service: api@internal
healthcheck:
  interval: 10s
builder:
  multiarch: false
